#macro GENRE_NUM 10
#macro PREF_GENRE_CHANCE 50
#macro NEIGH_GENRE_CHANCE 5

#macro AGENT_SPEED_MIN 3
#macro AGENT_SPEED_RAND 5
#macro AGENT_SPEED AGENT_SPEED_MIN + random(AGENT_SPEED_RAND)

#macro AGENT_SPAWN_COUNTDOWN_MIN 3
#macro AGENT_SPAWN_COUNTDOWN_RAND 10
#macro AGENT_SPAWN_COUNTDOWN AGENT_SPAWN_COUNTDOWN_MIN + irandom(AGENT_SPAWN_COUNTDOWN_RAND)